Update build_and_deploy_dotnet.yml

diff --git a/.github/workflows/build_and_deploy_dotnet.yml b/.github/workflows/build_and_deploy_dotnet.yml
--- a/.github/workflows/build_and_deploy_dotnet.yml
+++ b/.github/workflows/build_and_deploy_dotnet.yml
@@ -49,6 +49,14 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v2
 
+    - name: Check for prerelease packages
+      if: ${{!startsWith(github.ref, 'refs/tags/prerelease-')}}
+      run: |
+        if grep -q "<PackageReference .* Version=\".*-prerelease\"" *.csproj; then
+          echo "Solution is containing prerelease packages, abort!"
+          exit 1
+        fi
+
     - name: Get .NET version
       working-directory: src
       id: dotnet-version
